# Generated by Django 4.2.3 on 2023-07-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='your_class',
            field=models.CharField(blank=True, choices=[('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten'), ('11', 'Eleven'), ('12', 'Twelve')], max_length=2, null=True),
        ),
    ]
