# Generated by Django 4.2.3 on 2023-07-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0002_alter_studentprofile_your_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone_no',
            field=models.CharField(max_length=11, verbose_name='Phone Number'),
        ),
    ]
