# Generated by Django 4.2.3 on 2023-07-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0003_alter_teacherprofile_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number'),
        ),
    ]
