# Generated by Django 4.2.3 on 2023-07-08 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_login', '0003_alter_teacherprofile_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_login.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AnswarQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answar', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_student.askedquestion')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_login.teacherprofile')),
            ],
        ),
    ]
