# Generated by Django 4.2.3 on 2023-07-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_teacher', '0003_quizanswar'),
    ]

    operations = [
        migrations.AddField(
            model_name='articale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_image'),
        ),
    ]
