# Generated by Django 4.2.3 on 2023-07-08 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_teacher', '0005_alter_quizanswar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswar',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='App_teacher.quiz'),
        ),
    ]
