# Generated by Django 4.2.3 on 2023-07-08 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0003_alter_teacherprofile_phone_no'),
        ('App_teacher', '0006_alter_quizanswar_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articale',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='App_login.teacherprofile'),
        ),
    ]
