# Generated by Django 4.2.3 on 2023-07-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_teacher', '0007_alter_articale_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswar',
            name='answar',
        ),
    ]
