# Generated by Django 4.2.3 on 2023-07-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_teacher', '0008_remove_quizanswar_answar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'catagories',
            },
        ),
        migrations.AddField(
            model_name='articale',
            name='catagory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='articale_catagori', to='App_teacher.catagory'),
            preserve_default=False,
        ),
    ]
