# Generated by Django 4.2.3 on 2023-07-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_teacher', '0009_catagory_articale_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articale',
            name='catagory',
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
